import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import aiworkerSidebar from './sidebars/aiworker';
import hx5d20Sidebar from './sidebars/hx5d20';
import omySidebar from './sidebars/omy';
import omxSidebar from './sidebars/omx';

/**
 * Hand-curated sidebars mirroring source/_data/navigation.yml ordering.
 * dxlSidebar follows the original ROBOTIS e-Manual structure:
 *   DYNAMIXEL overview → Quick start → Y, P, X, MX, AX → Protocol/CRC → EX, DX, RX (legacy) → PRO
 */
const sidebars: SidebarsConfig = {
  dxlQuickStartSidebar: [
    'dxl/index',
    'dxl/dxl-quick-start-guide',
    'dxl/dxl-quick-start-insert',
  ],

  dxlSidebar: [
    {
      type: 'category',
      label: 'Y Series',
      link: {type: 'doc', id: 'dxl/y/index'},
      items: [{type: 'autogenerated', dirName: 'dxl/y'}],
    },
    {
      type: 'category',
      label: 'P Series',
      link: {type: 'doc', id: 'dxl/p/index'},
      items: [{type: 'autogenerated', dirName: 'dxl/p'}],
    },
    {
      type: 'category',
      label: 'X Series',
      link: {type: 'doc', id: 'dxl/x/x'},
      items: [
        {type: 'autogenerated', dirName: 'dxl/x'},
        'dxl/x_c',
        'dxl/x_h',
        'dxl/x_l',
        'dxl/x_m',
      ],
    },
    {
      type: 'category',
      label: 'MX Series',
      link: {type: 'doc', id: 'dxl/mx'},
      items: [{type: 'autogenerated', dirName: 'dxl/mx'}],
    },
    {
      type: 'category',
      label: 'AX Series',
      link: {type: 'doc', id: 'dxl/ax'},
      items: [{type: 'autogenerated', dirName: 'dxl/ax'}],
    },

    {
      type: 'category',
      label: 'EX Series',
      link: {type: 'doc', id: 'dxl/ex'},
      items: [{type: 'autogenerated', dirName: 'dxl/ex'}],
    },
    {
      type: 'category',
      label: 'DX Series',
      link: {type: 'doc', id: 'dxl/dx'},
      items: [{type: 'autogenerated', dirName: 'dxl/dx'}],
    },
    {
      type: 'category',
      label: 'RX Series',
      link: {type: 'doc', id: 'dxl/rx'},
      items: [{type: 'autogenerated', dirName: 'dxl/rx'}],
    },
    {
      type: 'category',
      label: 'PRO Series',
      link: {type: 'doc', id: 'dxl/pro/pro'},
      items: [
        {type: 'autogenerated', dirName: 'dxl/pro'},
        'dxl/pro_h',
        'dxl/pro_l',
        'dxl/pro_m',
      ],
    },
  ],
  protocolSidebar: [
    'dxl/protocol1',
    'dxl/protocol2',
    'dxl/crc',
  ],
  /*
   * Systems 소분류별 사이드바.
   * Mega-menu 의 각 제품 링크는 그 제품 폴더 안의 페이지로 향하므로,
   * 폴더 단위로 autogenerated 사이드바를 두면 사용자가 페이지에 진입했을 때
   * 그 제품 전용 사이드바만 보인다. sidebars 객체 키 순서가 검색 우선순위라
   * 좁은 범위(제품 폴더) 사이드바를 systemsSidebar 보다 먼저 둔다.
   */
  aiworkerSidebar,
  aisapiensSidebar: [
    {
      type: 'category',
      label: 'AI Sapiens',
      link: {type: 'doc', id: 'systems/aisapiens/introduction_ai_sapiens'},
      items: ['systems/aisapiens/introduction_ai_sapiens'],
    },
  ],
  opSidebar: [
    {
      type: 'category',
      label: 'ROBOTIS OP',
      link: {type: 'generated-index'},
      items: [{type: 'autogenerated', dirName: 'systems/op'}],
    },
  ],
  op2Sidebar: [
    {
      type: 'category',
      label: 'ROBOTIS OP2',
      link: {type: 'generated-index'},
      items: [{type: 'autogenerated', dirName: 'systems/op2'}],
    },
  ],
  op3Sidebar: [
    {
      type: 'category',
      label: 'ROBOTIS OP3',
      link: {type: 'generated-index'},
      items: [{type: 'autogenerated', dirName: 'systems/op3'}],
    },
  ],
  thormang3Sidebar: [
    {
      type: 'category',
      label: 'ROBOTIS THORMANG3',
      link: {type: 'generated-index'},
      items: [{type: 'autogenerated', dirName: 'systems/thormang3'}],
    },
  ],
  hx5d20Sidebar,
  rhp12rnSidebar: [
    {
      type: 'category',
      label: 'RH-P12-RN',
      link: {type: 'generated-index'},
      items: [{type: 'autogenerated', dirName: 'systems/rh_p12_rn'}],
    },
  ],
  omySidebar,
  omxSidebar,
  openmanipulatorPSidebar: [
    {
      type: 'category',
      label: 'OpenMANIPULATOR-P',
      link: {type: 'generated-index'},
      items: [{type: 'autogenerated', dirName: 'systems/openmanipulator_p'}],
    },
  ],
  openmanipulatorXSidebar: [
    {
      type: 'category',
      label: 'OpenMANIPULATOR-X',
      link: {type: 'generated-index'},
      items: [{type: 'autogenerated', dirName: 'systems/openmanipulator_x'}],
    },
  ],
  manipulatorHSidebar: [
    {
      type: 'category',
      label: 'Manipulator H',
      link: {type: 'generated-index'},
      items: [{type: 'autogenerated', dirName: 'systems/manipulator_h'}],
    },
  ],
  /* TurtleBot3 은 mega-menu가 /docs/category/turtlebot3 (generated-index)
   * 로 연결되므로 사이드바 루트를 category 로 감싸 인덱스 페이지를 만든다. */
  turtlebot3Sidebar: [
    {
      type: 'category',
      label: 'TurtleBot3',
      link: {type: 'generated-index'},
      items: [{type: 'autogenerated', dirName: 'systems/turtlebot3'}],
    },
  ],
  systemsSidebar: [
    'systems/index',
    'systems/ai_manipulator_main',
    'systems/rh_p12_rn_main',
    {
      type: 'category',
      label: 'Common',
      link: {type: 'generated-index'},
      items: [{type: 'autogenerated', dirName: 'systems/common'}],
    },
    {
      type: 'category',
      label: 'ROS Messages',
      link: {type: 'generated-index'},
      items: [{type: 'autogenerated', dirName: 'systems/msgs'}],
    },
  ],
  softwareSidebar: [{type: 'autogenerated', dirName: 'software'}],
  partsSidebar: [{type: 'autogenerated', dirName: 'parts'}],
  eduSidebar: [{type: 'autogenerated', dirName: 'edu'}],
  faqSidebar: [{type: 'autogenerated', dirName: 'faq'}],
};

export default sidebars;
