import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const dxlQuickStartSidebar: SidebarsConfig[string] = [
  'dxl/index',
  'dxl/dxl-quick-start-guide',
  'dxl/dxl-quick-start-insert',
];

const dxlSidebar: SidebarsConfig[string] = [
  'dxl/index',
  'dxl/dxl-quick-start-guide',
  {
    type: 'category',
    label: 'Model Reference',
    link: {type: 'generated-index'},
    items: [
      {
        type: 'category',
        label: 'Y Series',
        link: {type: 'doc', id: 'dxl/y/index'},
        items: [{type: 'autogenerated', dirName: 'dxl/y'}],
      },
      {
        type: 'category',
        label: 'P Series',
        link: {type: 'doc', id: 'dxl/p/index'},
        items: [{type: 'autogenerated', dirName: 'dxl/p'}],
      },
      {
        type: 'category',
        label: 'X Series',
        link: {type: 'doc', id: 'dxl/x/x'},
        items: [
          {type: 'autogenerated', dirName: 'dxl/x'},
          'dxl/x_c',
          'dxl/x_h',
          'dxl/x_l',
          'dxl/x_m',
        ],
      },
      {
        type: 'category',
        label: 'MX Series',
        link: {type: 'doc', id: 'dxl/mx'},
        items: [{type: 'autogenerated', dirName: 'dxl/mx'}],
      },
      {
        type: 'category',
        label: 'AX Series',
        link: {type: 'doc', id: 'dxl/ax'},
        items: [{type: 'autogenerated', dirName: 'dxl/ax'}],
      },
      {
        type: 'category',
        label: 'EX Series',
        link: {type: 'doc', id: 'dxl/ex'},
        items: [{type: 'autogenerated', dirName: 'dxl/ex'}],
      },
      {
        type: 'category',
        label: 'DX Series',
        link: {type: 'doc', id: 'dxl/dx'},
        items: [{type: 'autogenerated', dirName: 'dxl/dx'}],
      },
      {
        type: 'category',
        label: 'RX Series',
        link: {type: 'doc', id: 'dxl/rx'},
        items: [{type: 'autogenerated', dirName: 'dxl/rx'}],
      },
      {
        type: 'category',
        label: 'PRO Series',
        link: {type: 'doc', id: 'dxl/pro/pro'},
        items: [
          {type: 'autogenerated', dirName: 'dxl/pro'},
          'dxl/pro_h',
          'dxl/pro_l',
          'dxl/pro_m',
        ],
      },
    ],
  },
  {
    type: 'category',
    label: 'Protocol',
    link: {type: 'generated-index'},
    items: [
      'dxl/protocol1',
      'dxl/protocol2',
      'dxl/crc',
    ],
  },
];

const protocolSidebar: SidebarsConfig[string] = [
  'dxl/protocol1',
  'dxl/protocol2',
  'dxl/crc',
];

export {dxlQuickStartSidebar, dxlSidebar, protocolSidebar};
