import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const doc = (id: string, label: string) => ({type: 'doc' as const, id, label, key: id});

const dynamixelSdkSidebar: SidebarsConfig[string] = [
  doc('software/dynamixel_sdk/dynamixel_sdk', 'DYNAMIXEL SDK'),
  doc('software/dynamixel_sdk/overview', 'Overview'),
  doc('software/dynamixel_sdk/quick_start_guide', 'Quick Start Guide'),
  doc('software/dynamixel_sdk/download', 'Download SDK'),
  doc('software/dynamixel_sdk/device_setup', 'Device Setup'),
  {
    type: 'category',
    label: 'Library Setup',
    link: {type: 'doc', id: 'software/dynamixel_sdk/library_setup'},
    items: [
      doc('software/dynamixel_sdk/library_setup/c', 'C'),
      doc('software/dynamixel_sdk/library_setup/cpp', 'C++'),
      doc('software/dynamixel_sdk/library_setup/python', 'Python'),
      doc('software/dynamixel_sdk/library_setup/java', 'Java'),
      doc('software/dynamixel_sdk/library_setup/csharp', 'C#'),
      doc('software/dynamixel_sdk/library_setup/matlab', 'MATLAB'),
      doc('software/dynamixel_sdk/library_setup/labview', 'LabVIEW'),
    ],
  },
  {
    type: 'category',
    label: 'Basic Read/Write Tutorial',
    link: {type: 'doc', id: 'software/dynamixel_sdk/basic_read_write_tutorial/basic_read_write_tutorial'},
    items: [
      doc('software/dynamixel_sdk/basic_read_write_tutorial/cpp', 'C++'),
      doc('software/dynamixel_sdk/basic_read_write_tutorial/python', 'Python'),
    ],
  },
  {
    type: 'category',
    label: 'Sync Read/Write Tutorial',
    link: {type: 'doc', id: 'software/dynamixel_sdk/sync_read_write_tutorial/sync_read_write_tutorial'},
    items: [
      doc('software/dynamixel_sdk/sync_read_write_tutorial/cpp', 'C++'),
      doc('software/dynamixel_sdk/sync_read_write_tutorial/python', 'Python'),
    ],
  },
  {
    type: 'category',
    label: 'Bulk Read/Write Tutorial',
    link: {type: 'doc', id: 'software/dynamixel_sdk/bulk_read_write_tutorial/bulk_read_write_tutorial'},
    items: [
      doc('software/dynamixel_sdk/bulk_read_write_tutorial/cpp', 'C++'),
      doc('software/dynamixel_sdk/bulk_read_write_tutorial/python', 'Python'),
    ],
  },
  {
    type: 'category',
    label: 'API Reference',
    items: [{type: 'autogenerated', dirName: 'software/dynamixel_sdk/api_reference'}],
  },
  {
    type: 'category',
    label: 'Sample Code',
    items: [{type: 'autogenerated', dirName: 'software/dynamixel_sdk/sample_code'}],
  },
  doc('software/dynamixel_sdk/quick_start_video', 'Quick Start Video'),
  doc('software/dynamixel_sdk/faq', 'FAQ'),
];

export default dynamixelSdkSidebar;
