import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const doc = (id: string, label: string) => ({type: 'doc' as const, id, label, key: id});
const category = (key: string, label: string, items: SidebarsConfig[string]) => ({
  type: 'category' as const,
  key,
  label,
  items,
});

const dynamixelSdkSidebar: SidebarsConfig[string] = [
  doc('software/dynamixel_sdk/dynamixel_sdk', 'DYNAMIXEL SDK'),
  doc('software/dynamixel_sdk/overview', 'Overview'),
  doc('software/dynamixel_sdk/quick_start_guide', 'Quick Start Guide'),
  doc('software/dynamixel_sdk/download', 'Download SDK'),
  doc('software/dynamixel_sdk/device_setup', 'Device Setup'),
  {
    type: 'category',
    label: 'Library Setup',
    link: {type: 'doc', id: 'software/dynamixel_sdk/library_setup'},
    items: [
      doc('software/dynamixel_sdk/library_setup/c', 'C'),
      doc('software/dynamixel_sdk/library_setup/cpp', 'C++'),
      doc('software/dynamixel_sdk/library_setup/python', 'Python'),
      doc('software/dynamixel_sdk/library_setup/java', 'Java'),
      doc('software/dynamixel_sdk/library_setup/csharp', 'C#'),
      doc('software/dynamixel_sdk/library_setup/matlab', 'MATLAB'),
      doc('software/dynamixel_sdk/library_setup/labview', 'LabVIEW'),
    ],
  },
  {
    type: 'category',
    label: 'Basic Read/Write Tutorial',
    link: {type: 'doc', id: 'software/dynamixel_sdk/basic_read_write_tutorial/basic_read_write_tutorial'},
    items: [
      doc('software/dynamixel_sdk/basic_read_write_tutorial/cpp', 'C++'),
      doc('software/dynamixel_sdk/basic_read_write_tutorial/python', 'Python'),
    ],
  },
  {
    type: 'category',
    label: 'Sync Read/Write Tutorial',
    link: {type: 'doc', id: 'software/dynamixel_sdk/sync_read_write_tutorial/sync_read_write_tutorial'},
    items: [
      doc('software/dynamixel_sdk/sync_read_write_tutorial/cpp', 'C++'),
      doc('software/dynamixel_sdk/sync_read_write_tutorial/python', 'Python'),
    ],
  },
  {
    type: 'category',
    label: 'Bulk Read/Write Tutorial',
    link: {type: 'doc', id: 'software/dynamixel_sdk/bulk_read_write_tutorial/bulk_read_write_tutorial'},
    items: [
      doc('software/dynamixel_sdk/bulk_read_write_tutorial/cpp', 'C++'),
      doc('software/dynamixel_sdk/bulk_read_write_tutorial/python', 'Python'),
    ],
  },
  category('dynamixel-sdk-api-reference', 'API Reference', [
    category('dynamixel-sdk-api_reference-c', "C", [
      doc('software/dynamixel_sdk/api_reference/c/c_porthandler', "PortHandler"),
      doc('software/dynamixel_sdk/api_reference/c/c_packethandler', "PacketHandler"),
      doc('software/dynamixel_sdk/api_reference/c/c_groupbulkread', "GroupBulkRead"),
      doc('software/dynamixel_sdk/api_reference/c/c_groupbulkwrite', "GroupBulkWrite"),
      doc('software/dynamixel_sdk/api_reference/c/c_groupsyncread', "GroupSyncRead"),
      doc('software/dynamixel_sdk/api_reference/c/c_groupsyncwrite', "GroupSyncWrite"),
    ]),
    category('dynamixel-sdk-api_reference-cpp', "C++", [
      doc('software/dynamixel_sdk/api_reference/cpp/cpp_porthandler', "PortHandler"),
      doc('software/dynamixel_sdk/api_reference/cpp/cpp_packethandler', "PacketHandler"),
      doc('software/dynamixel_sdk/api_reference/cpp/cpp_groupbulkread', "GroupBulkRead"),
      doc('software/dynamixel_sdk/api_reference/cpp/cpp_groupbulkwrite', "GroupBulkWrite"),
      doc('software/dynamixel_sdk/api_reference/cpp/cpp_groupsyncread', "GroupSyncRead"),
      doc('software/dynamixel_sdk/api_reference/cpp/cpp_groupsyncwrite', "GroupSyncWrite"),
    ]),
    category('dynamixel-sdk-api_reference-python', "Python", [
      doc('software/dynamixel_sdk/api_reference/python/python_porthandler', "PortHandler"),
      doc('software/dynamixel_sdk/api_reference/python/python_packethandler', "PacketHandler"),
      doc('software/dynamixel_sdk/api_reference/python/python_groupbulkread', "GroupBulkRead"),
      doc('software/dynamixel_sdk/api_reference/python/python_groupbulkwrite', "GroupBulkWrite"),
      doc('software/dynamixel_sdk/api_reference/python/python_groupsyncread', "GroupSyncRead"),
      doc('software/dynamixel_sdk/api_reference/python/python_groupsyncwrite', "GroupSyncWrite"),
    ]),
    category('dynamixel-sdk-api_reference-java', "Java", [
      doc('software/dynamixel_sdk/api_reference/java/java_porthandler', "PortHandler"),
      doc('software/dynamixel_sdk/api_reference/java/java_packethandler', "PacketHandler"),
      doc('software/dynamixel_sdk/api_reference/java/java_groupbulkread', "GroupBulkRead"),
      doc('software/dynamixel_sdk/api_reference/java/java_groupbulkwrite', "GroupBulkWrite"),
      doc('software/dynamixel_sdk/api_reference/java/java_groupsyncread', "GroupSyncRead"),
      doc('software/dynamixel_sdk/api_reference/java/java_groupsyncwrite', "GroupSyncWrite"),
    ]),
    category('dynamixel-sdk-api_reference-csharp', "C#", [
      doc('software/dynamixel_sdk/api_reference/csharp/csharp_porthandler', "PortHandler"),
      doc('software/dynamixel_sdk/api_reference/csharp/csharp_packethandler', "PacketHandler"),
      doc('software/dynamixel_sdk/api_reference/csharp/csharp_groupbulkread', "GroupBulkRead"),
      doc('software/dynamixel_sdk/api_reference/csharp/csharp_groupbulkwrite', "GroupBulkWrite"),
      doc('software/dynamixel_sdk/api_reference/csharp/csharp_groupsyncread', "GroupSyncRead"),
      doc('software/dynamixel_sdk/api_reference/csharp/csharp_groupsyncwrite', "GroupSyncWrite"),
    ]),
    category('dynamixel-sdk-api_reference-matlab', "MATLAB", [
      doc('software/dynamixel_sdk/api_reference/matlab/matlab_porthandler', "PortHandler"),
      doc('software/dynamixel_sdk/api_reference/matlab/matlab_packethandler', "PacketHandler"),
      doc('software/dynamixel_sdk/api_reference/matlab/matlab_groupbulkread', "GroupBulkRead"),
      doc('software/dynamixel_sdk/api_reference/matlab/matlab_groupbulkwrite', "GroupBulkWrite"),
      doc('software/dynamixel_sdk/api_reference/matlab/matlab_groupsyncread', "GroupSyncRead"),
      doc('software/dynamixel_sdk/api_reference/matlab/matlab_groupsyncwrite', "GroupSyncWrite"),
    ]),
    category('dynamixel-sdk-api_reference-labview', "LabVIEW", [
      doc('software/dynamixel_sdk/api_reference/labview/labview_porthandler', "PortHandler"),
      doc('software/dynamixel_sdk/api_reference/labview/labview_packethandler', "PacketHandler"),
      doc('software/dynamixel_sdk/api_reference/labview/labview_groupbulkread', "GroupBulkRead"),
      doc('software/dynamixel_sdk/api_reference/labview/labview_groupbulkwrite', "GroupBulkWrite"),
      doc('software/dynamixel_sdk/api_reference/labview/labview_groupsyncread', "GroupSyncRead"),
      doc('software/dynamixel_sdk/api_reference/labview/labview_groupsyncwrite', "GroupSyncWrite"),
    ]),
  ]),
  category('dynamixel-sdk-sample-code', 'Sample Code', [
    category('dynamixel-sdk-sample_code-c', "C", [
      doc('software/dynamixel_sdk/sample_code/c/broadcast_ping_protocol_2_0', "C Broadcast Ping Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/c/bulk_read_protocol_1_0', "C Bulk Read Protocol 1.0"),
      doc('software/dynamixel_sdk/sample_code/c/bulk_read_write_protocol_2_0', "C Bulk Read Write Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/c/clear_multi_turn_protocol_2_0', "C Clear Multi Turn Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/c/dxl_monitor', "C Dxl Monitor"),
      doc('software/dynamixel_sdk/sample_code/c/indirect_address_protocol_2_0', "C Indirect Address Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/c/multi_port_protocol_1_0', "C Multi Port Protocol 1.0"),
      doc('software/dynamixel_sdk/sample_code/c/multi_port_protocol_2_0', "C Multi Port Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/c/ping_protocol_1_0', "C Ping Protocol 1.0"),
      doc('software/dynamixel_sdk/sample_code/c/ping_protocol_2_0', "C Ping Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/c/protocol_combined', "C Protocol Combined"),
      doc('software/dynamixel_sdk/sample_code/c/read_write_protocol_1_0', "C Read Write Protocol 1.0"),
      doc('software/dynamixel_sdk/sample_code/c/read_write_protocol_2_0', "C Read Write Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/c/reboot_protocol_2_0', "C Reboot Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/c/reset_protocol_1_0', "C Reset Protocol 1.0"),
      doc('software/dynamixel_sdk/sample_code/c/reset_protocol_2_0', "C Reset Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/c/sync_read_write_protocol_2_0', "C Sync Read Write Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/c/sync_write_protocol_1_0', "C Sync Write Protocol 1.0"),
    ]),
    category('dynamixel-sdk-sample_code-cpp', "C++", [
      doc('software/dynamixel_sdk/sample_code/cpp/broadcast_ping_protocol_2_0', "C++ Broadcast Ping Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/cpp/bulk_read_protocol_1_0', "C++ Bulk Read Protocol 1.0"),
      doc('software/dynamixel_sdk/sample_code/cpp/bulk_read_write_protocol_2_0', "C++ Bulk Read Write Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/cpp/clear_multi_turn_protocol_2_0', "C++ Clear Multi Turn Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/cpp/dxl_monitor', "C++ Dxl Monitor"),
      doc('software/dynamixel_sdk/sample_code/cpp/indirect_address_protocol_2_0', "C++ Indirect Address Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/cpp/multi_port_protocol_1_0', "C++ Multi Port Protocol 1.0"),
      doc('software/dynamixel_sdk/sample_code/cpp/multi_port_protocol_2_0', "C++ Multi Port Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/cpp/ping_protocol_1_0', "C++ Ping Protocol 1.0"),
      doc('software/dynamixel_sdk/sample_code/cpp/ping_protocol_2_0', "C++ Ping Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/cpp/protocol_combined', "C++ Protocol Combined"),
      doc('software/dynamixel_sdk/sample_code/cpp/read_write_protocol_1_0', "C++ Read Write Protocol 1.0"),
      doc('software/dynamixel_sdk/sample_code/cpp/read_write_protocol_2_0', "C++ Read Write Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/cpp/reboot_protocol_2_0', "C++ Reboot Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/cpp/reset_protocol_1_0', "C++ Reset Protocol 1.0"),
      doc('software/dynamixel_sdk/sample_code/cpp/reset_protocol_2_0', "C++ Reset Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/cpp/sync_read_write_protocol_2_0', "C++ Sync Read Write Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/cpp/sync_write_protocol_1_0', "C++ Sync Write Protocol 1.0"),
    ]),
    category('dynamixel-sdk-sample_code-python', "Python", [
      doc('software/dynamixel_sdk/sample_code/python/broadcast_ping_protocol_2_0', "Python Broadcast Ping Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/python/bulk_read_protocol_1_0', "Python Bulk Read Protocol 1.0"),
      doc('software/dynamixel_sdk/sample_code/python/bulk_read_write_protocol_2_0', "Python Bulk Read Write Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/python/clear_multi_turn_protocol_2_0', "Python Clear Multi Turn Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/python/indirect_address_protocol_2_0', "Python Indirect Address Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/python/multi_port_protocol_1_0', "Python Multi Port Protocol 1.0"),
      doc('software/dynamixel_sdk/sample_code/python/multi_port_protocol_2_0', "Python Multi Port Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/python/ping_protocol_1_0', "Python Ping Protocol 1.0"),
      doc('software/dynamixel_sdk/sample_code/python/ping_protocol_2_0', "Python Ping Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/python/protocol_combined', "Python Protocol Combined"),
      doc('software/dynamixel_sdk/sample_code/python/read_write_protocol_1_0', "Python Read Write Protocol 1.0"),
      doc('software/dynamixel_sdk/sample_code/python/read_write_protocol_2_0', "Python Read Write Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/python/reboot_protocol_2_0', "Python Reboot Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/python/reset_protocol_1_0', "Python Reset Protocol 1.0"),
      doc('software/dynamixel_sdk/sample_code/python/reset_protocol_2_0', "Python Reset Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/python/sync_read_write_protocol_2_0', "Python Sync Read Write Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/python/sync_write_protocol_1_0', "Python Sync Write Protocol 1.0"),
    ]),
    category('dynamixel-sdk-sample_code-java', "Java", [
      doc('software/dynamixel_sdk/sample_code/java/broadcast_ping_protocol_2_0', "Java Broadcast Ping Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/java/bulk_read_protocol_1_0', "Java Bulk Read Protocol 1.0"),
      doc('software/dynamixel_sdk/sample_code/java/bulk_read_write_protocol_2_0', "Java Bulk Read Write Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/java/clear_multi_turn_protocol_2_0', "Java Clear Multi Turn Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/java/indirect_address_protocol_2_0', "Java Indirect Address Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/java/multi_port_protocol_1_0', "Java Multi Port Protocol 1.0"),
      doc('software/dynamixel_sdk/sample_code/java/multi_port_protocol_2_0', "Java Multi Port Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/java/ping_protocol_1_0', "Java Ping Protocol 1.0"),
      doc('software/dynamixel_sdk/sample_code/java/ping_protocol_2_0', "Java Ping Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/java/protocol_combined', "Java Protocol Combined"),
      doc('software/dynamixel_sdk/sample_code/java/read_write_protocol_1_0', "Java Read Write Protocol 1.0"),
      doc('software/dynamixel_sdk/sample_code/java/read_write_protocol_2_0', "Java Read Write Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/java/reboot_protocol_2_0', "Java Reboot Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/java/reset_protocol_1_0', "Java Reset Protocol 1.0"),
      doc('software/dynamixel_sdk/sample_code/java/reset_protocol_2_0', "Java Reset Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/java/sync_read_write_protocol_2_0', "Java Sync Read Write Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/java/sync_write_protocol_1_0', "Java Sync Write Protocol 1.0"),
    ]),
    category('dynamixel-sdk-sample_code-csharp', "C#", [
      doc('software/dynamixel_sdk/sample_code/csharp/broadcast_ping_protocol_2_0', "C# Broadcast Ping Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/csharp/bulk_read_protocol_1_0', "C# Bulk Read Protocol 1.0"),
      doc('software/dynamixel_sdk/sample_code/csharp/bulk_read_write_protocol_2_0', "C# Bulk Read Write Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/csharp/clear_multi_turn_protocol_2_0', "C# Clear Multi Turn Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/csharp/indirect_address_protocol_2_0', "C# Indirect Address Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/csharp/multi_port_protocol_1_0', "C# Multi Port Protocol 1.0"),
      doc('software/dynamixel_sdk/sample_code/csharp/multi_port_protocol_2_0', "C# Multi Port Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/csharp/ping_protocol_1_0', "C# Ping Protocol 1.0"),
      doc('software/dynamixel_sdk/sample_code/csharp/ping_protocol_2_0', "C# Ping Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/csharp/protocol_combined', "C# Protocol Combined"),
      doc('software/dynamixel_sdk/sample_code/csharp/read_write_protocol_1_0', "C# Read Write Protocol 1.0"),
      doc('software/dynamixel_sdk/sample_code/csharp/read_write_protocol_2_0', "C# Read Write Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/csharp/reboot_protocol_2_0', "C# Reboot Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/csharp/reset_protocol_1_0', "C# Reset Protocol 1.0"),
      doc('software/dynamixel_sdk/sample_code/csharp/reset_protocol_2_0', "C# Reset Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/csharp/sync_read_write_protocol_2_0', "C# Sync Read Write Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/csharp/sync_write_protocol_1_0', "C# Sync Write Protocol 1.0"),
    ]),
    category('dynamixel-sdk-sample_code-matlab', "MATLAB", [
      doc('software/dynamixel_sdk/sample_code/matlab/broadcast_ping_protocol_2_0', "MATLAB Broadcast Ping Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/matlab/bulk_read_protocol_1_0', "MATLAB Bulk Read Protocol 1.0"),
      doc('software/dynamixel_sdk/sample_code/matlab/bulk_read_write_protocol_2_0', "MATLAB Bulk Read Write Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/matlab/clear_multi_turn_protocol_2_0', "MATLAB Clear Multi Turn Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/matlab/indirect_address_protocol_2_0', "MATLAB Indirect Address Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/matlab/multi_port_protocol_1_0', "MATLAB Multi Port Protocol 1.0"),
      doc('software/dynamixel_sdk/sample_code/matlab/multi_port_protocol_2_0', "MATLAB Multi Port Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/matlab/ping_protocol_1_0', "MATLAB Ping Protocol 1.0"),
      doc('software/dynamixel_sdk/sample_code/matlab/ping_protocol_2_0', "MATLAB Ping Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/matlab/protocol_combined', "MATLAB Protocol Combined"),
      doc('software/dynamixel_sdk/sample_code/matlab/read_write_protocol_1_0', "MATLAB Read Write Protocol 1.0"),
      doc('software/dynamixel_sdk/sample_code/matlab/read_write_protocol_2_0', "MATLAB Read Write Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/matlab/reboot_protocol_2_0', "MATLAB Reboot Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/matlab/reset_protocol_1_0', "MATLAB Reset Protocol 1.0"),
      doc('software/dynamixel_sdk/sample_code/matlab/reset_protocol_2_0', "MATLAB Reset Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/matlab/sync_read_write_protocol_2_0', "MATLAB Sync Read Write Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/matlab/sync_write_protocol_1_0', "MATLAB Sync Write Protocol 1.0"),
    ]),
    category('dynamixel-sdk-sample_code-labview', "LabVIEW", [
      doc('software/dynamixel_sdk/sample_code/labview/broadcast_ping_protocol_2_0', "LabVIEW Broadcast Ping Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/labview/bulk_read_protocol_1_0', "LabVIEW Bulk Read Protocol 1.0"),
      doc('software/dynamixel_sdk/sample_code/labview/bulk_read_write_protocol_2_0', "LabVIEW Bulk Read Write Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/labview/clear_multi_turn_protocol_2_0', "LabVIEW Clear Multi Turn Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/labview/indirect_address_protocol_2_0', "LabVIEW Indirect Address Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/labview/multi_port_protocol_1_0', "LabVIEW Multi Port Protocol 1.0"),
      doc('software/dynamixel_sdk/sample_code/labview/multi_port_protocol_2_0', "LabVIEW Multi Port Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/labview/ping_protocol_1_0', "LabVIEW Ping Protocol 1.0"),
      doc('software/dynamixel_sdk/sample_code/labview/ping_protocol_2_0', "LabVIEW Ping Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/labview/protocol_combined', "LabVIEW Protocol Combined"),
      doc('software/dynamixel_sdk/sample_code/labview/read_write_protocol_1_0', "LabVIEW Read Write Protocol 1.0"),
      doc('software/dynamixel_sdk/sample_code/labview/read_write_protocol_2_0', "LabVIEW Read Write Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/labview/reboot_protocol_2_0', "LabVIEW Reboot Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/labview/reset_protocol_1_0', "LabVIEW Reset Protocol 1.0"),
      doc('software/dynamixel_sdk/sample_code/labview/reset_protocol_2_0', "LabVIEW Reset Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/labview/sync_read_write_protocol_2_0', "LabVIEW Sync Read Write Protocol 2.0"),
      doc('software/dynamixel_sdk/sample_code/labview/sync_write_protocol_1_0', "LabVIEW Sync Write Protocol 1.0"),
    ]),
  ]),
  doc('software/dynamixel_sdk/quick_start_video', 'Quick Start Video'),
  doc('software/dynamixel_sdk/faq', 'FAQ'),
];

export default dynamixelSdkSidebar;
