import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const manipulatorHSidebar: SidebarsConfig[string] = [
  {
    type: 'category',
    label: 'Manipulator H',
    link: {type: 'generated-index'},
    items: [{type: 'autogenerated', dirName: 'systems/manipulator_h'}],
  },
];

export default manipulatorHSidebar;
