import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const opSidebar: SidebarsConfig[string] = [
  {
    type: 'category',
    label: 'ROBOTIS OP',
    items: [{type: 'autogenerated', dirName: 'systems/op'}],
  },
];

export default opSidebar;
