import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const op2Sidebar: SidebarsConfig[string] = [
  {
    type: 'category',
    label: 'ROBOTIS OP2',
    items: [{type: 'autogenerated', dirName: 'systems/op2'}],
  },
];

export default op2Sidebar;
