import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const op3Sidebar: SidebarsConfig[string] = [
  {
    type: 'category',
    label: 'ROBOTIS OP3',
    link: {type: 'generated-index'},
    items: [{type: 'autogenerated', dirName: 'systems/op3'}],
  },
];

export default op3Sidebar;
