import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const openmanipulatorPSidebar: SidebarsConfig[string] = [
  {
    type: 'category',
    label: 'OpenMANIPULATOR-P',
    link: {type: 'generated-index'},
    items: [{type: 'autogenerated', dirName: 'systems/openmanipulator_p'}],
  },
];

export default openmanipulatorPSidebar;
