import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const openmanipulatorXSidebar: SidebarsConfig[string] = [
  {
    type: 'category',
    label: 'OpenMANIPULATOR-X',
    link: {type: 'generated-index'},
    items: [{type: 'autogenerated', dirName: 'systems/openmanipulator_x'}],
  },
];

export default openmanipulatorXSidebar;
