import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const rhp12rnSidebar: SidebarsConfig[string] = [
  {
    type: 'category',
    label: 'RH-P12-RN',
    link: {type: 'generated-index'},
    items: [{type: 'autogenerated', dirName: 'systems/rh_p12_rn'}],
  },
];

export default rhp12rnSidebar;
