import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const softwareSidebar: SidebarsConfig[string] = [
  {type: 'autogenerated', dirName: 'software'},
];

export default softwareSidebar;
