import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const systemsSidebar: SidebarsConfig[string] = [
  'systems/index',
  'systems/ai_manipulator_main',
  {
    type: 'category',
    label: 'Common',
    items: [{type: 'autogenerated', dirName: 'systems/common'}],
  },
  {
    type: 'category',
    label: 'ROS Messages',
    items: [{type: 'autogenerated', dirName: 'systems/msgs'}],
  },
];

export default systemsSidebar;
