import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const thormang3Sidebar: SidebarsConfig[string] = [
  {
    type: 'category',
    label: 'ROBOTIS THORMANG3',
    link: {type: 'generated-index'},
    items: [{type: 'autogenerated', dirName: 'systems/thormang3'}],
  },
];

export default thormang3Sidebar;
