import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const turtlebot3Sidebar: SidebarsConfig[string] = [
  {
    type: 'category',
    label: 'TurtleBot3',
    link: {type: 'generated-index'},
    items: [{type: 'autogenerated', dirName: 'systems/turtlebot3'}],
  },
];

export default turtlebot3Sidebar;
